version: "3"

services:
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=config.yaml"]
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - "3100:3100"   # tempo
      - "9411:9411"   #zipkin